services:
  # PostgreSQL Database
  - type: pserv
    name: crm-postgres-db
    runtime: postgresql
    plan: free
    region: oregon
    
  # Spring Boot Backend
  - type: web
    name: crm-backend
    runtime: java
    plan: free
    region: oregon
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/crm-system-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: crm-postgres-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
